DSSMOD-1181
ACF-CB-NYTD/Cypress_Modernization pull request #10
Opened 2024-08-28 17:17 UTC by TylerFSmith2

2024-08-30 20:11 UTC, wyntonjones requested changes
The jira ticket I think was copied from the SA automation test, so it has information related to federal users, but the ticket also includes criteria for verifying the user details page (after you select the hyperlink). Should we include those scenarios here or sperate test? I didn't review the SA UAM test, but make the corrections mentioned here in that test if they apply.

2024-08-30 20:11 UTC, wyntonjones commented on cypress/e2e/User Account Management/SystemAdminUser.js
remove spaces from folder name.

2024-08-31 00:56 UTC, TylerFSmith2 commented on cypress/e2e/User Account Management/SAOUser.js
> +        userAccountManagement.elements.secondaryRoleChildren().get('[data-testid="checkbox"]').eq(1).click();
What part of this section do you want defined in the object file?

2024-08-31 00:58 UTC, TylerFSmith2 commented on cypress/e2e/User Account Management/SAOUser.js
> +        userAccountManagement.typeNameSearchInput('Deleted');
In another comment you mention wanting to break up the filters. Let's connect and discuss how these kinds of tests should be approached.

2024-08-31 01:00 UTC, TylerFSmith2 commented on cypress/e2e/User Account Management/SAOUser.js
> +        userAccountManagement.elements.secondaryRoleChildren().get('[data-testid="checkbox"]').eq(0).click();
Is this talking about the clickOnSecondaryRoleDropdown or secondaryRoleChildren?

2024-09-03 16:03 UTC, TylerFSmith2 commented on cypress/e2e/User Account Management/SAOUser.js
> +        userAccountManagement.elements.secondaryRoleChildren().get('[data-testid="checkbox"]').eq(0).click();
userAccountManagement.elements.secondaryRoleChildren().get('[data-testid="checkbox"]').eq(0)

Change this to a .click function

2024-09-03 16:16 UTC, TylerFSmith2 commented on cypress/e2e/User Account Management/SAOUser.js
> +    it("Verify Regional and CB Office Staff users will not be able to access the User Account Management page.", function () {
For above comment - Check to make sure hyperlink is tested. Adjust ticket for both that and removing any SA content.

2024-09-04 20:13 UTC, wyntonjones requested changes

2024-09-04 20:13 UTC, wyntonjones commented on cypress/e2e/UserAccountManagement/SAOUser.js
> +    it.only("Verify the Manage User Account Requests button works", function () {
line 118 - remove "only"

2024-09-04 20:25 UTC, wyntonjones approved these changes

2024-09-04 20:26 UTC, merged