My profile
ACF-CB-NYTD/Cypress_Modernization pull request #15
Opened 2024-10-04 13:14 UTC by mincho-cb-nytd

2024-10-09 21:06 UTC, wyntonjones requested changes
I only reviewed the CB central my profile test. Make those corrections and apply them, if necessary to the other specs. Be sure to verify button text in the page object file and if the button brings up a modal, verify the modal text, they can be done in its own test within the spec.

2024-10-09 21:06 UTC, wyntonjones commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
>  });
After saving i dont see steps that verify the changes made. And then you need to change it back to the original information.

Also a test to make the changes but not save them, there will be a unsaved changes modal.

2024-10-09 21:19 UTC, wyntonjones requested changes

2024-10-09 21:19 UTC, wyntonjones commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        commonPage.verifyUrl('/User/Profile');
This should be a new test. "Verify the my profile user information changed" or something like that.

2024-10-09 21:19 UTC, wyntonjones commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.enterDefaultUsernamePasswordAndPhone('cypress', 'cb', '5082460311');
Make this its own test "Change user information back to original user information"

2024-10-11 16:08 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        viewMyProfile.elements.myProfileFirstLastName().should('have.text', 'cypress cb')
resolved

2024-10-15 23:14 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
>      commonPage.clickOnMyProfileSelect();
it a a dropdown option thats why is named as select...

2024-10-16 16:36 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.elements.receivesEmailNotificationsText().should('have.text', 'Receive Email Notifications? *');
resolved

2024-10-16 19:27 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.elements.phoneText().should('have.text', 'Phone *');
Added step to verify username text box, Unable to too add verification for username text due to button is disabled

2024-10-17 01:59 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.elements.primaryRoleText().should('have.text', 'Primary Role');
done

2024-10-17 02:35 UTC, mincho-cb-nytd commented on cypress/e2e/pages/EditMyProfilePageObjects.js
> +    clickOnPreviewEdits() {
this is already verify on line number 20

2024-10-17 02:36 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.elements.previewEditsButton().should('have.text', 'Preview Edits');
done

2024-10-17 02:37 UTC, mincho-cb-nytd commented on cypress/e2e/pages/EditMyProfilePageObjects.js
> +    clickOnSaveEdits() {
line 133 verifying the text

2024-10-17 17:13 UTC, mincho-cb-nytd commented on cypress/e2e/My Profile/CBCentralUserMyProfile.js
> +        editMyProfile.enterDefaultUsernamePasswordAndPhone('cypress', 'cb', '5082460311');
resolved

2024-10-22 16:06 UTC, TylerFSmith2 reviewed
I did not mark every instance of a mng locator, please be sure to replace all of them.

2024-10-28 16:41 UTC, merged